### ISSUE TITLE
Unable to run models bigger than 320x320

### ISSUE THREAD

**Issue by ss13ms110** [WasabiFan/tidl-custom-model-demo#1]
Hello WasabiFan,

This is Shubham Sharma. I have modified your code little bit to run pre-compiled models from TIDL.

I am currently able to run `ONR-OD-8040-ssd-lite-regNetX-200mf-fpn-bgr-mmdet-coco-320x320` from TIDL model_zoo.

However, if I try to run any model other than this one for example, `ONR-OD-8030-ssd-lite-mobv2-fpn-mmdet-coco-512x512` or `ONR-OD-8050-ssd-lite-regNetX-800mf-fpn-bgr-mmdet-coco-512x512` or `ONR-OD-8230-yolox-m-lite-mmdet-coco-640x640` the BB AI-64 crashes and my terminal hangs, without giving any error or warning.

This was also the case when I was running edge_ai_app from TIDL. But, your code made it possible to atleast run 320x320 model.

Please help me as I am struggling with this for long time.

Thank you

**Comment by ss13ms110** [comment]
There was a power problem. I was using laptop power supply but, now I am using 5V 3A type-c power supply and it's no more crashing.

Thank you

**Comment by WasabiFan** [comment]
Sorry for the lack of reply! I have too many GitHub notifications and this one got lost. I'm glad to hear you worked it out!

Yeah, originally I was powering my board off a 2A wall adapter with a barrel jack, but it would shut down when under load. I bought an official Raspberry Pi brand USB-C wall adapter (I think they're rated to 3A) and haven't had the issue since. I also bought an inline USB-C power monitor (shows negotiated/effective voltage, active current draw and their product) and keep that in the loop so I can monitor overall power draw to understand what I need when powering it on a mobile robot.
